version: '3'

services:
  db:
    image: postgres:14.2
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: car_rest_api
    ports:
      - "5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    depends_on:
      db:
        condition: service_healthy

    #command: python manage.py runserver 0.0.0.0:8000
#    mapping local files to Docker files (automatically)
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db:db
    networks:
      - backend

networks:
  backend:
    driver: bridge